[package]
name = "jwt-explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.10"
directories-next = "2.0"
iced = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"