[package]
name = "jwt-explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
crypto-hashes = { version = "0.9", features = ["include_weak"] }
druid = { git = "https://github.com/linebender/druid", features = ["im"] }
env_logger = "0.9"
hmac = "0.11"
jwt = "0.15"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"